# Generated by Django 4.2.8 on 2023-12-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptocurrencyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('cryptocurrency_name', models.TextField(max_length=6)),
                ('price', models.FloatField()),
            ],
        ),
    ]
